In [1]:
#a370d87cf86527e40f03d3aec85c9607628fd1763b9d0e15

In [140]:
import platform
# What version of Python do you have?
import sys

import keras
import pandas as pd
import sklearn as sk
import tensorflow as tf

print(f"Python Platform: {platform.platform()}")
print(f"Tensor Flow Version: {tf.__version__}")
print(f"Keras Version: {keras.__version__}")
print()
print(f"Python {sys.version}")
print(f"Pandas {pd.__version__}")
print(f"Scikit-Learn {sk.__version__}")
gpu = len(tf.config.list_physical_devices('GPU')) > 0
print("GPU is", "available" if gpu else "NOT AVAILABLE")

Python Platform: macOS-13.5.1-arm64-arm-64bit
Tensor Flow Version: 2.13.0
Keras Version: 2.13.1

Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ]
Pandas 2.0.3
Scikit-Learn 1.3.0
GPU is available


In [141]:
tf.__version__

'2.13.0'

In [142]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [5]:
scalar = tf.constant(7)
scalar

2023-09-06 19:45:40.342196: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2023-09-06 19:45:40.342258: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2023-09-06 19:45:40.342274: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2023-09-06 19:45:40.343224: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:303] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-09-06 19:45:40.343425: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:269] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [7]:
tf.random.set_seed(3)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [8]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Other ways to make tensors

In [9]:
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [10]:
tf.zeros((10, 7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Can convert numpy arrays to tensors

In [11]:
import numpy as np

np_A = np.arange(1, 25, dtype=np.int32)
np_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [12]:
A = tf.constant(np_A, shape=(2, 3, 4))
b = tf.constant(np_A)
C = tf.constant(np_A, shape=(3, 8))
A, b, C

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>)

In [13]:
A.ndim, b.ndim, C.ndim

(3, 1, 2)

#### Getting information from tensors

When dealing with tensors we want to be aware of the following attributes
* Shape
* Rank
* Axis or Dimension
* Size

In [14]:
rank_4_tensors = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensors

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [15]:
rank_4_tensors[1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [16]:
rank_4_tensors.ndim

4

In [17]:
tf.size(rank_4_tensors)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [18]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensors.dtype)
print("Number of dimensions (rank):", rank_4_tensors.ndim)
print("Shape of tensor:", rank_4_tensors.shape)
print("Elements along the 0 axis:", rank_4_tensors.shape[0])
print("Elements along the last axis:", rank_4_tensors.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensors))
print("Total number of elements in our tensor as a single element:", tf.size(rank_4_tensors).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor as a single element: 120


### Indexing tensors
Tensors can be indexed just like lists

In [19]:
rank_4_tensors[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [20]:
rank_4_tensors[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [21]:
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [22]:
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [23]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]  # `...` means every axis of the tensor like `:, :` in this case
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [24]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [25]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating Tensors (tensor operations)

*** Basic Operations ***
`+`, `-`, `*`, `/`

In [26]:
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [27]:
# Addition
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [28]:
# Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [29]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [30]:
# We can use the tf in-build functions too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [31]:
# Division
tf.divide(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [32]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

### ***Matrix Multiplication***

In ML the most common operation is Matrix Multiplication the `.` product

In [33]:
tensor_1 = tf.constant([[10, 7],
                        [3, 4]])
tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [34]:
tf.random.set_seed(42)
tensor_2 = tf.random.shuffle(tensor_1)
tensor_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7]], dtype=int32)>

In [35]:
tensor_1, tensor_2, tensor_1 * tensor_2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 3,  4],
        [10,  7]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[30, 28],
        [30, 28]], dtype=int32)>)

In [36]:
tensor_1 = tf.constant([[1, 2, 5], [7, 2, 1], [3, 3, 3]])
tensor_2 = tf.constant([[3, 5], [6, 7], [1, 8]])
tensor_1, tensor_2

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [37]:
tensor_1 @ tensor_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [38]:
tf.matmul(tensor_1, tensor_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

### Changing the datatype of a tensor

In [46]:
# Create a new tensor with default DataType (float32)
B = tf.constant([1.7, 7.4])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [47]:
C = tf.constant([7, 10])
C, C.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>,
 tf.int32)

#### Reduced Precision

In [48]:
B_reduced = tf.cast(B, dtype=tf.float16)
B_reduced, B_reduced.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [51]:
C_reduced = tf.cast(C, tf.int16)
C_reduced, C_reduced.dtype

(<tf.Tensor: shape=(2,), dtype=int16, numpy=array([ 7, 10], dtype=int16)>,
 tf.int16)

### Aggregating Tensors

Aggregating tensors = Condensing tensors from multiple values down to smaller amount of values
```
Basically Stats
```

In [53]:
# Get the absolute values
D = tf.constant([-7, -10])
D, tf.abs(D)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)

Let's go through the following forms of aggregation:
* Minimum
* Maximum
* Mean
* Sum

In [58]:
random_tensor = tf.random.uniform([50], maxval=100, dtype=tf.int64)
random_tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([34, 68,  2, 24, 70, 91, 71, 33,  4, 67, 96, 68, 40, 48, 79, 31, 50,
       27, 85, 95,  0, 11, 61, 62, 16, 56, 18, 58, 86,  2, 26, 14, 87, 85,
       64,  5, 91, 25, 30, 93, 60, 24, 96, 23, 76, 39, 13, 24,  8, 67])>

In [60]:
tf.size(random_tensor), random_tensor.shape, random_tensor.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [61]:
tf.reduce_min(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [64]:
tf.reduce_max(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [63]:
tf.reduce_mean(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [65]:
tf.reduce_sum(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=2403>

***Challenge:*** Find the variance and std. deviation of the above tensor

In [68]:
random_tensor_float_32 = tf.cast(random_tensor, dtype=tf.float32)

In [69]:
tf.math.reduce_variance(random_tensor_float_32)

<tf.Tensor: shape=(), dtype=float32, numpy=920.7364>

In [70]:
tf.math.reduce_std(random_tensor_float_32)

<tf.Tensor: shape=(), dtype=float32, numpy=30.343637>

### Find the positional maximum and minimum of a tensor

Useful when the neural network outputs the prediction probabilities

In [90]:
tf.random.set_seed(42)
randon_tensor_for_pos_max = tf.random.uniform([50])
randon_tensor_for_pos_max

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [91]:
tf.math.top_k(randon_tensor_for_pos_max, 1)

TopKV2(values=<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.9671384], dtype=float32)>, indices=<tf.Tensor: shape=(1,), dtype=int32, numpy=array([42], dtype=int32)>)

In [92]:
# For maximum
tf.argmax(randon_tensor_for_pos_max)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [93]:
randon_tensor_for_pos_max[tf.argmax(randon_tensor_for_pos_max)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [94]:
randon_tensor_for_pos_max[tf.argmax(randon_tensor_for_pos_max)] == tf.reduce_max(randon_tensor_for_pos_max)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [95]:
# For minimum
tf.argmin(randon_tensor_for_pos_max)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [96]:
randon_tensor_for_pos_max[tf.argmin(randon_tensor_for_pos_max)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single dimensions)

In [104]:
tf.random.set_seed(42)
tensor_to_squeeze = tf.constant(tf.random.uniform(shape=[50]), shape=[1, 1, 1, 50, 1])
tensor_to_squeeze

<tf.Tensor: shape=(1, 1, 1, 50, 1), dtype=float32, numpy=
array([[[[[0.6645621 ],
          [0.44100678],
          [0.3528825 ],
          [0.46448255],
          [0.03366041],
          [0.68467236],
          [0.74011743],
          [0.8724445 ],
          [0.22632635],
          [0.22319686],
          [0.3103881 ],
          [0.7223358 ],
          [0.13318717],
          [0.5480639 ],
          [0.5746088 ],
          [0.8996835 ],
          [0.00946367],
          [0.5212307 ],
          [0.6345445 ],
          [0.1993283 ],
          [0.72942245],
          [0.54583454],
          [0.10756552],
          [0.6767061 ],
          [0.6602763 ],
          [0.33695042],
          [0.60141766],
          [0.21062577],
          [0.8527372 ],
          [0.44062173],
          [0.9485276 ],
          [0.23752594],
          [0.81179297],
          [0.5263394 ],
          [0.494308  ],
          [0.21612847],
          [0.8457197 ],
          [0.8718841 ],
          [0.3083862 ],
      

In [105]:
tensor_to_squeeze.shape

TensorShape([1, 1, 1, 50, 1])

In [106]:
squeezed_tensor = tf.squeeze(tensor_to_squeeze)
squeezed_tensor, squeezed_tensor.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-Hot encoding

In [110]:
# Create a list of indices
some_list = [0, 1, 2, 3] # i.e., read, green, blue and purple.

# One-Hot encoding out list:
tf.one_hot(some_list, depth=len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [113]:
tf.one_hot(some_list, depth=2)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [111]:
# On and Off custom values for One-Hot encoding
tf.one_hot(some_list, depth=4, on_value="Hai", off_value="Hola")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Hai', b'Hola', b'Hola', b'Hola'],
       [b'Hola', b'Hai', b'Hola', b'Hola'],
       [b'Hola', b'Hola', b'Hai', b'Hola'],
       [b'Hola', b'Hola', b'Hola', b'Hai']], dtype=object)>

In [112]:
tf.one_hot(some_list, depth=4, on_value=1024, off_value=0)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1024,    0,    0,    0],
       [   0, 1024,    0,    0],
       [   0,    0, 1024,    0],
       [   0,    0,    0, 1024]], dtype=int32)>

### Some Math functions
* Squaring
* Log
* Square Root

In [115]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [116]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [118]:
H_float = tf.cast(H, dtype=tf.float32)

In [122]:
tf.math.log(H_float)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [125]:
tf.sqrt(H_float)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

### Tensors & NumPy

Tensorflow interacts beautifully with NumPy arrays.
Tensorflow tensors can run on a GPU are TPU for faster computation.

In [133]:
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [134]:
J_np = np.array(J)
J_np, type(J_np)

(array([ 3.,  7., 10.]), numpy.ndarray)

In [135]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [136]:
# Default types of TF and NP are slightly different
# Numpy has higher bit and tensorflow has lower bit
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [146]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

***Note:*** If you have access to CUDA-enabled GPU, TensorFlow will automatically use it whenever possible. 